### ISSUE TITLE
For the latest release, is there still a CommonJS version provided?

### ISSUE THREAD

**Issue by SinTan1071** [uport-project/veramo#1162]
Hope the latest release can still provide a CommonJS version.

**Comment by mirceanis** [comment]
The latest release (5+) doesn't provide a CommonJS version anymore.
We debated this major change a lot but since the whole javascript world is moving in this direction, and we are also dependent on some ESM packages already, we saw no point in maintaining a CommonJS output.

The easiest way forward is for you to transition your project to ESM as well. Our [5.0 release notes](https://github.com/uport-project/veramo/releases/tag/v5.0.0) link to some guides about how to do that.

If you're unable to transition now, you'll have to use dynamic imports to load the Veramo packages in your commonJS codebase:

```js
const { createAgent } = await import('@veramo/core')
// instead of 
import { createAgent } from '@veramo/core'
```

If you're using typescript and running into issues with dynamic imports, perhaps [this resource](https://github.com/TypeStrong/ts-node/discussions/1290) helps.

I'm closing this as it's unlikely we'll reinstate the CommonJS output, but please reopen if you are encountering issues as a discussing solutions in public might be helpful for others too.

**Comment by SinTan1071** [comment]
@mirceanis thx
