### ISSUE TITLE
multiple sendTransactions in short time: same nonce -> replacement transaction underpriced

### ISSUE THREAD

**Issue by nikolockenvitz** [uport-project/veramo#223]
Hi,

when I send a few transactions in a short time, only the first one goes through. In the debug log I see the following error message:

```
daf:ethr-did:identity-controller [ethjs-query] while formatting outputs from RPC '{"value":{"code":-32000,"message":"replacement transaction underpriced"}}'
```

To give you a reproducable example I created an [minimal example repository](https://github.com/nikolockenvitz/daf-test-replacement-transaction-underpriced) where I add two services (one right after the other). The first one works but the second one will fail:
```js
for (let i = 0; i < 2; i++) {
  const result = await identity.identityController.addService({
    type: "TestService", serviceEndpoint: `https://${i}.testservice.example.com`,
  });
}
```

Based on the debug error message I came to the conclusion that both transactions use the same nonce and thus the second one is rejected.
The cause seems to be in [ethjs-provider-signer](https://github.com/ethjs/ethjs-provider-signer/blob/master/src/index.js#L51-L64) where the transaction count is retrieved and used as nonce. Somehow the previous transaction didn't increment the count yet (maybe because it's not yet in a block?) so the same nonce will be used again.

Possible fixes (?):
* resolve Promise returned by `addService()` after transaction is validated
* make sure transactionCount also counts unvalidated transactions (&rarr; not an issue in this repo)
* inject a nonce based on the knowledge that there is some pending transaction (?)

If I understand everything correctly I think this might be a bug of how transactionCount works and should be fixed there? Can anyone confirm this? Then it would not be a bug in this repo but somewhere else. In parallel I will investigate this further to find the root cause.

Maybe something similar: When I run `getDidDocument()` right after adding a service, the service is not yet there (probably transaction is sent but not yet validated in a block).

**Comment by mirceanis** [comment]
Thank you for reporting this.
Kudos on the very detailed bug report!

Indeed, the generic solution is to use `eth_getTransactionCount` with the `pending` block param ( the use of `latest` is because of legacy reasons, it is not meant to be a general solution).
Depending on the security and consistency constraints, some apps may not want to do this by default, though. So there should be some flexibility here.

We plan to switch to [ethers.js](https://github.com/ethers-io/ethers.js/) as the ethereum layer since it has some nice features that would help here, like using a `Promise` to resolve the `nonce`.
This will be done first in `ethr-did` since that is where the logic for this boils to.
This needs to be paired with some more flexibility to override some transaction parameters when calling these methods from DAF.

relates to #224 #205
