### ISSUE TITLE
ethjs is discontinued and contains security vulnerabilities

### ISSUE THREAD

**Issue by nikolockenvitz** [uport-project/veramo#224]
[ethjs](https://github.com/ethjs) libraries are used in this repo but they are discontinued (see [this](https://github.com/ethjs/ethjs-signer/pull/6#issuecomment-678499125) and [this](https://github.com/ethjs/ethjs-provider-signer/issues/1#issuecomment-678500660) comment).

Even if PRs are still accepted packages would also need to be relased to use these updates. As you can see [in this PR](https://github.com/ethjs/ethjs-signer/pull/6) they still depend on vulnerable versions of other packages and as they specified the version exactly, it's hard to update to the fixed version.

IMO they should be replaced. Is that already planned or are you working on that already / how is the progress/timeline?

This also affects other repos, e.g. [ethr-did](https://github.com/uport-project/ethr-did)

**Comment by mirceanis** [comment]
Thank you for spotting this.
We are aware of the deprecation and had already started moving to the ethers.js backbone for ETH operations.
The update will have to happen first in [ethr-did](https://github.com/uport-project/ethr-did) since that is the principal dependent, and a small correction needs to be done in DAF after that to adapt to the new API.
