### ISSUE TITLE
[proposal] Allow for storage of received VCs

### ISSUE THREAD

**Issue by rkreutzer** [uport-project/veramo#363]
The system allows scanning of a QR Code containing a JWT of a verifiable credential. A user would typically be scanning this QR Code to accept a VC issued by someone else to them. The createVerifiableCredential method requires the issuer DID to exist in the user's DID table and it signs the VC with that DID.

A storeVerifiableCredential method could be added that validates that the subject DID exists in the user's DID table, then stores the credential. While this could be added to the current CredentialIssuer class, a Credential Manager class could be created, along with methods to list, get and delete credentials.

**Comment by simonas-notcat** [comment]
You can [already do this](https://github.com/uport-project/veramo/blob/next/__tests__/shared/messageHandler.ts#L23) by passing scanned QR data to the `handleMessage` method with `save: true`

```typescript
  const qrCode = 'eyJ0eXAiOiJKV1QiLCJhbGciOiJFUzI1Nkst...'
  parsedMessage = await agent.handleMessage({
    raw: qrCode,
    save: true,
    metaData: [{ type: 'qrcode' }],
  })
```

**Comment by rkreutzer** [comment]
That would blindly save whatever was scanned, I guess. If a user scans a VC, I want to display it and prompt them to approve before saving. I also want to do verification on the subject DID and expiration.

I've currently added that logic to my app and then call dataStoreSaveVerifiableCredential to save it.

**Comment by mirceanis** [comment]
I think that calling `dataStoreSaveVerifiableCredential ` is the right way of doing it.

It's true that adding the `save: true` argument to `handleMessage` would blindly store any valid VC, which is why the `save` parameter will probably be removed in a future version.

That being said, I'm not sure I understand the original proposal.
The functions of the proposed `CredentialManager` API are achieved by the `data-store` package with the `DataStore` and `DataStoreORM` plugins.
Is the proposal to invoke the `dataStoreSaveVerifiableCredential` method only when the subject DID is in the local database?

(Note that the expiration checks are automatically done by the `handleMessage` method if you are using the `did-jwt` plugin)
