### ISSUE TITLE
At some values for r & s of the signature provided when overriding `signJWT(...)`, an exception happen: 'Unexpected end of data'

### ISSUE THREAD

**Issue by Muhammad-Altabba** [uport-project/veramo#477]
**Bug severity**
4

**Describe the bug**
At some values for r & s of the signature, an exception `Unexpected end of data` is thrown.
The exception came only once in about 10 or 15 times run. So, most of the time there is no issue. But at some cases, the error came.

**Context and code Snippet**
We are implementing a Veram Plugin that overrides the signing functionality to depend on a local KMS (Key Management System) micro-service. I am getting the signature for our micro-service and then getting the `r` and `s` from it using https://www.npmjs.com/package/elliptic.
Here is a code snippet from our plugin where we overrides `signJWT` as follow:

```
// Some issue with `import { ec } from 'elliptic'`. But, then `ec.Signature` is undefined!
//  For that, the following `require` is used:
const Signature = require('elliptic/lib/elliptic/ec/signature');
...

export class KeyManagementSystem extends AbstractKeyManagementSystem {

...

async signJWT({
    key,
    data,
  }: {
    key: IKey;
    data: string;
  }): Promise<EcdsaSignature> {
let signatureString;
    try {
      const response = await axios.post(
        KMS_ENDPOINT,
        {
          encPrivKey: key.privateKeyHex,
          value: data,
        }
      );

      signatureString = response.data.signature;
      l.debug(
        signatureString,
        'KeyManagementSystem -> signJWT: signatureString'
      );

      const signature = new Signature(signatureString, 'hex');
      const r = signature.r.toString('hex');
      const s = signature.s.toString('hex');

      return {
        r,
        s,
        recoveryParam: 1,
      };
    } catch (error) {
      l.error(signatureString);
      l.error(error);
      throw error;
    }
  }
}
```

Here is a sample of the values when the exception came:

Singature: 3044022011983f0ada761e32b39cbcefd4e08c6b2a50c722c9a6270d5215065e8c969f79022008e1d16494e84826c6c88908d09f58cb92d098fc17be652d08f2263c3e0454e9
r: 11983f0ada761e32b39cbcefd4e08c6b2a50c722c9a6270d5215065e8c969f79
s: 8e1d16494e84826c6c88908d09f58cb92d098fc17be652d08f2263c3e0454e9

**Observed behavior**
At some values for `r` and `s` the following exception happen:
```
    SyntaxError: Unexpected end of data
        at decode (/rep-path/node_modules/multibase/src/rfc4648.js:52:11)
        at Object.decode (/rep-path/node_modules/multibase/src/rfc4648.js:118:14)
        at Base.decode (/rep-path/node_modules/multibase/src/base.js:46:23)
        at Object.u8a [as fromString] (/rep-path/node_modules/uint8arrays/from-string.js:47:29)
        at toJose (/rep-path/node_modules/did-jwt/src/util.ts:53:12)
        at /rep-path/node_modules/did-jwt/src/SignerAlgorithm.ts:12:14
        at processTicksAndRejections (internal/process/task_queues.js:93:5)
```   

**Versions (please complete the following information):**
 - Veramo: 1.1.0
 - Node Version: 12.13.0

**Comment by mirceanis** [comment]
It's very exciting to hear that you are working on a veramo plugin!
We would love to see it in action, if you open-source it.

About your question, the reason this is happening is that the signature components need to be 32 bytes, which when serialized to hex, should be 64 characters per component.
In some cases, one or both of the components will serialize to a hex-string smaller than 64 characters, and in that situation they need to be left-padded with zeroes.
In your example, the `s` component is only 63 characters long. It should be left-padded, so that it looks like this:
`08e1d16494e84826c6c88908d09f58cb92d098fc17be652d08f2263c3e0454e9`

You can use a method like this one to do the padding:
```typescript
function leftpad(data: string, size = 64): string {
  if (data.length === size) return data
  return '0'.repeat(size - data.length) + data
}
```

That being said, there are a few extra notes to be taken here.
I believe the KMS micro-service should be the one dealing with privateKeys, and that the other veramo plugins should be unaware of what the private keys are.
```
      const response = await axios.post(
        KMS_ENDPOINT,
        {
          encPrivKey: key.privateKeyHex, // here it's probably best to transmit the `key.kid` instead
          value: data,
        }
      );
```

I realize that the `kms-local` and `kms-local-react` are not very good examples of dealing with private key material, but that is about to change soon.
We will be making some changes to the KMS layer in veramo so that crypto operations don't rely on key material, but on functionality. This should make things more production-friendly.

I'm closing this issue now, but please reopen if there are still issues related to this.

**Comment by mirceanis** [comment]
Oh, also, if you're not using `recoveryParam` then it's better to leave it out instead of putting a hardcoded value there.

**Comment by Muhammad-Altabba** [comment]
Many thanks @mirceanis for your valuable input.
This resolved the issue. We will inform you once the code of the plugin is available :)

However, regarding the `recoveryParam`, it is not optional inside `EcdsaSignature`. And the return type of `async signJWT(...)` is  `Promise<EcdsaSignature>`. So, I am not able to leave it out without having a typescript error.

**Comment by mirceanis** [comment]
Glad to hear it worked.
Regarding `EcdsaSignature`, it will not be required in the next major update. We'll be simplifying some of the signing API so that signatures have the same type for all elliptic curves and algorithms. Most likely `Base64` strings or raw `Uint8Array`.
You can test your code against upcoming major changes by using the `@next` releases of the veramo packages.
