### ISSUE TITLE
Build issue when upgrading to version 1.2.x

### ISSUE THREAD

**Issue by rkreutzer** [uport-project/veramo#546]
**Bug severity**
4

**Describe the bug**
After upgrading from version 1.0.1 to version 1.2.0 (or @latest or @next), the build step for my app fails with:
Error: ./node_modules/did-jwt/lib/index.js 1:4514 -- Module parse failed: Unexpected token (1:4514) -- You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file.

It appears to point to the statement with the first use of Optional Chaining in that program.

I've tried to upgrade and downgrade did-jwt, but still the same issue. I also tried adding resolutions to downgrade it in the package.json. Any ideas?

**Versions:**
 - Veramo: 1.2.x
 - OS: Windows 10
 - Node: 14.16.0
 - npm: 6.14.13
 - ionic: 6.16.1
 - angular: 8.3.29
 - yarn: 1.22.10
 - typescript: 4.3.2

**Comment by mirceanis** [comment]
We've seen a similar error before and it was fixed by using node 14 to build (but you seem to already be using node14).

In your case I suspect it might be an issue with your babel config.
Perhaps this will help https://medium.com/@iamjasonchild/optional-chaining-in-javascript-via-babel7-e83c07127d62

Also, possibly related issues:
https://github.com/decentralized-identity/did-jwt/pull/175
https://github.com/decentralized-identity/did-jwt/issues/168

**Comment by jasonhealy** [comment]
@rkreutzer 

I have the `JwtMessageHandler` working as expected in ionic (serving locally in chrome) by adding a polyfill to `polyfill.ts`

```
(window as any).global = window;
// @ts-ignore
window.Buffer = window.Buffer || require('buffer').Buffer;
```

Can you add this and let me know if your issue persists?

**Comment by rkreutzer** [comment]
It appears that the way I upgraded was the issue. I had done a "yarn upgrade" command listing all the @veramo modules and that apparently caused the issue. I deleted the node_modules folder, updated the version numbers in the package.json file, then did a "yarn install". That cleared the issue.

Jason, I already had similar statements in the polyfills file, but thanks.
