### ISSUE TITLE
Add did:github provider?

### ISSUE THREAD

**Issue by Arxcis** [uport-project/veramo#784]
**Is your feature request related to a problem? Please describe.**
I would like to quickly prototype a network of agents representing public organizations issuing and requesting credentials  over DIDComm. Here is an example of a QR out-of-band messaging refering to the DIDs of two public institutions:

```json
{
    "typ": "application/didcomm-plain+json",
    "type": "https://didcomm.org/out-of-band/2.0/invitation",
    "id": "<id used for context as pthid>",
    "from": "did:github:HappyCars",                                          // <-- did:github
    "body": {
        "goal-code": "id.happycars.start-car-rental",
        "goal": "Rent a car from Happy Cars Inc",
        "requires": [
            { 
                    "type": "DriversLicense", 
                   "issuer": "did:github:TheOfficialTrafficAuthority"               // <-- did:github
            }
        ]
    }
}
```

I currently only see providers for `did:eth` , `did:web` and `did:key` . 
- did:eth provider - https://github.com/uport-project/veramo/blob/next/packages/did-provider-ethr/src/ethr-did-provider.ts
- did:key provider - https://github.com/uport-project/veramo/blob/next/packages/did-provider-key/src/key-did-provider.ts
- did:web provider - https://github.com/uport-project/veramo/blob/next/packages/did-provider-web/src/web-did-provider.ts (implementation missing for addService)

```
% veramo did create
? Select identifier provider (Use arrow keys)
❯ did:ethr 
  did:ethr:rinkeby 
  did:ethr:ropsten 
  did:ethr:kovan 
  did:ethr:goerli 
  did:web 
  did:key 
```

**Describe the solution you'd like**

- I would like to be able to do `veramo did create`  and select `did:github` . Then also do `veramo did add-service`  to add a `DIDCommMessaging` endpoint.
- After this has happened I would expect the `index.jsonld` DID-document to be updated @ `https://raw.githubusercontent.com/USERNAME/ghdid/master/index.jsonld`
-  did:github spec - https://github.com/decentralized-identity/github-did/blob/master/docs/did-method-spec/index.md)

**Describe alternatives you've considered**
- I have considered using the `did:eth`, but this has two downsides for my prototyping use-case: 1. It requires funding. 2. The identifiers which are created are not human-readable, like in my example above with the.
- I have considered waiting around to see if Veramo could support `did:3` running on Ceramic.

**Comment by mirceanis** [comment]
Hi @Arxcis
It should be fairly easy to to support such a provider in Veramo.
Veramo is extensible in many ways, so you could write your own provider for various DID methods.

We distinguish 2 aspects when it comes to supporting DID methods.
1. resolving a DID
2. creating/updating a DID document.

For `did:github`specifically, resolving should be really straight forward, as it is a simple HTTP fetch; very similar do `did:web`
Creating/updating would involve a little bit more work as it would require interacting with the github API. Not difficult, but also not just a single line of code.

You can take a look at how `@veramo/remote-server` [serves a DID document for a `did:web`](https://github.com/uport-project/veramo/blob/5202ef1dd51fd3b7ad57591fd726fdc571bc8492/packages/remote-server/src/web-did-doc-router.ts#L33). It's likely that a `did:github` provider would use a similar approach to construct the document for upload.

---

That being said, it should be relatively easy to use the existing `did:web` support from Veramo to point directly to a github hosted file, and update it manually, although with the current version of Veramo it would be a bit hacky:

1. Create a proxy DID:
```bash
veramo did create
# pick did:web
# use example.com as alias

veramo server
```

2. Then, in another terminal, run:
```bash
curl -H "host: example.com" localhost:3332/.well-known/did.json | sed "s/did:web:github.com/did:web:raw.githubusercontent.com:GITHUBUSERNAME:ghdid:main/g" > did.json
```
Of course, use the real github handle instead of `GITHUBUSERNAME`

3. upload the resulting did.json to your github.com/GITHUBUSERNAME/ghdid/did.json
4. resolve your new DID document to check:
```bash
veramo did resolve did:web:raw.githubusercontent.com:GITHUBUSERNAME:ghdid:main
```

Example:
```bash
veramo did resolve did:web:raw.githubusercontent.com:mirceanis:ghdid:main
```

You would do this every time you update your github hosted did:web

**Comment by Arxcis** [comment]
Thank you for the guide @mirceanis  🙏 

I tried to do what you suggested.

1. Create a did:web
```
% veramo did create
(node:8591) Warning: Accessing non-existent property 'abort' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
? Select identifier provider did:web
? Select key management system local
? Enter alias example.com
┌──────────┬─────────────┬─────────────────────┐
│ provider │       alias │                 did │
├──────────┼─────────────┼─────────────────────┤
│  did:web │ example.com │ did:web:example.com │
└──────────┴─────────────┴─────────────────────┘
```

2. Start the server:
```
 % veramo server
(node:8613) Warning: Accessing non-existent property 'abort' of module exports inside circular dependency
(Use `node --trace-warnings ...` to show where the warning was created)
🚀 Cloud Agent ready at http://localhost:3332
🆔 did:web:localhost
📨 Messaging endpoint http://localhost:3332/messaging
```

3. Curl for the did.json
```
% curl -H "host: example.com" localhost:3332/.well-known/did.json
{}%
```

I got an empty object as the result from my CURL. Do you spot an mistakes I did along the way?

**Comment by mirceanis** [comment]
Right, I forgot to specify that you need to use `@veramo/cli@next`

Can you try to run the server using `npx @veramo/cli@next server` and then running the `curl` command ?
It should be OK to use the same config file and database.

**Comment by Arxcis** [comment]
> Right, I forgot to specify that you need to use `@veramo/cli@next`
> 
> Can you try to run the server using `npx @veramo/cli@next server` and then running the `curl` command ? It should be OK to use the same config file and database.

This solved my issue. Thank you very much for the quick support 🙏 I think using `did:web` the way you have suggested here is OK for our use case for now. I will re-open this issue, if a decision to make a `did:github`-provider is made.
