### ISSUE TITLE
did:ethr:rsk and rsk:testnet are not resolving correctly

### ISSUE THREAD

**Issue by vgenev** [uport-project/veramo#893]
**Bug severity**
4

**Describe the bug**
When  trying to use Veramo with RSK (a fully compatible EVN, pegged to Bitcoin, which have it's own identity implementation, but based on uport 6.x.x) RIF Identity, the did is resolved wrongly.

```json
"did": "did:ethr:31:0x02809a71bb79e9ddc9d51c7e3eec32fd1879ee45b039cf2b2d0e78b0cfa7e337fe",
"provider": "did:ethr:rsk:testnet",
``` 

my plugins config for DID Manager and DID resolver are:

```javascript
[
 ....
    new DIDManager({
      store: new DIDStore(dbConnection),
      defaultProvider: "did:ethr:rsk:testnet",
      providers: {
        "did:ethr:rsk:testnet": new EthrDIDProvider({
          defaultKms: "local",
          network: 31,
          registry: "0xdca7ef03e98e0dc2b855be647c39abe984fcf21b",
          rpcUrl: "https://did.testnet.rsk.co:4444",
        }),
        "did:web": new WebDIDProvider({
          defaultKms: "local",
        }),
      },
    }),
    new DIDResolverPlugin({
      resolver: new Resolver({
        ...ethrDidResolver({
          networks: [
            {
              name: "rsk:testnet",
              chainId: 31,
              rpcUrl: "https://did.testnet.rsk.co:4444",
            },
          ],
        }),
        // ...webDidResolver(),
      }),
    }),
....
]
```

**To Reproduce**
Steps to reproduce the behaviour:
1. Follow the NodeJS tutorial
2. Add agent config as above
3. Try run `yarn id:create`
4. Check the returned value
5. Check also `yarn id:list` result is still the same
6. If you use RSK mainnet remove `:testnet` from the DID path and use `chainId: 30`

**Observed behaviour**
The RSK DID method is not resolving correctly, instead of `did:ethr:rsk:testnet` it is resolving `did:ethr:31` 
   
**Expected behaviour**
The DID created using the above config should resolve to `did:ethr:rsk:testnet`

**Details**
-

**Additional context**
-

**Version**
 - Veramo:
 ```json
"dependencies": {
    "@veramo/core": "^3.1.0",
    "@veramo/credential-w3c": "^3.1.0",
    "@veramo/data-store": "^3.1.0",
    "@veramo/did-manager": "^3.1.0",
    "@veramo/did-provider-ethr": "^3.1.0",
    "@veramo/did-provider-web": "^3.1.0",
    "@veramo/did-resolver": "^3.1.0",
    "@veramo/key-manager": "^3.1.0",
    "@veramo/kms-local": "^3.1.0",
    "ethr-did-resolver": "^5.0.4",
    "sqlite3": "^5.0.8",
    "uuid": "^8.3.2",
    "web-did-resolver": "^2.0.16"
  },
```
 - Node Version 16.4.2

**Comment by mirceanis** [comment]
This manifests when the DID is created by a provider for a non-standard network, and is caused by `@veramo/did-provide-ethr` missing a way to name the network and also not converting the non-standard network chain ID to hex.

For `rsk:testnet`, the DIDs should be created as: `did:ethr:0x1f:0xEthereumAddress`, but the hex conversion is not happening so the resolver then fails.

Standard networks should be resolvable using `did:ethr:<network name>:<0xAddressOrKey>` OR `did:ethr:<0x hex chain Id>:<0xAddressOrKey>`, while non-standard networks should only use the `<0x hex chainID>` format.
Networks are "standard" or "non-standard" based on the [Table of official deployments](https://github.com/uport-project/ethr-did-registry#contract-deployments), but this is not being enforced properly.
