### ISSUE TITLE
Add support for Bls12381G2 in the Credential-W3C package 

### ISSUE THREAD

**Issue by pcibraro** [uport-project/veramo#896]
The list of supported key types is hardcoded in the implementation. https://github.com/uport-project/veramo/blob/3a0765ef632aae29701004cbfbeb38a2de7bc847/packages/credential-w3c/src/action-handler.ts#L362

It would be ideal if the key type can be taken from the options so we can add support for other keys like Bls12381G2. I tried to extend it with a new suite but I found out that is actually not supported because of the type check in the line mentioned above.

**Comment by mirceanis** [comment]
This might be easier to do now after we added [support for specifying a particular key](https://github.com/uport-project/veramo/blob/5d62c52e28a504470f8ba2c2cbd3c38eed7f435f/packages/credential-w3c/src/action-handler.ts#L144) when signing credentials.

But you are right, the key type check has to be either extended or dropped and replaced with a mandatory parameter.

The reason these are the only key types hardcoded is because we use the bundled signers available in [`did-jwt`](https://github.com/decentralized-identity/did-jwt) and those key types are the only ones supported there.
There is no reason why those should be the only ones, but this does bring up a question of how to add support for new algorithm types in a more modular fashion.

**Comment by pcibraro** [comment]
Thanks a lot for looking into this. Yes, ignore what I said. I was able to get this working with did:web. Also the support for specifying the key will help a lot.
